# PyTorch Tensors — Basics
### Create Tensors

In [1]:
import torch

x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

r = torch.randn(3, 3)

z = torch.zeros(2, 3)
o = torch.ones(3, 2)

print(x, r, z, o)

tensor([[1., 2.],
        [3., 4.]]) tensor([[-1.3831, -0.2374, -0.0928],
        [ 0.7892,  0.4150,  0.8372],
        [ 0.4987,  0.0714,  0.2422]]) tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


### Check GPU availability

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("using device:", device )

using device: cpu


### move tensor to GPU

In [3]:
x_gpu = x.to(device)
x_gpu

tensor([[1., 2.],
        [3., 4.]])

### Tensor operation

In [4]:
a = torch.tensor([1,2, 3.], requires_grad=True)
b = a * 2
c = b.sum()

### Autograd

In [5]:
c.backward()
print(a.grad)

tensor([2., 2., 2.])


# TensorFlow Tensors — Basics
### Create Tensors

In [6]:
import tensorflow as tf

x = tf.constant([[1,2], [3,4]], dtype=tf.float32)
r = tf.random.normal((3,3))
z = tf.zeros((2,3))
o = tf.ones((3, 2))

print(x, r, z, o)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[-1.1135336   0.75688285  0.36673018]
 [-1.1948538   0.52519405 -0.0222281 ]
 [-0.4972808  -2.512241    0.71725017]], shape=(3, 3), dtype=float32) tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32) tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Check GPU

In [7]:
print("GPU available:", tf.config.list_physical_devices("GPU"))

GPU available: []


### Tensor operations

In [8]:
a = tf.Variable([1.0, 2.0, 3.0])
b = a * 2
c = tf.reduce_sum(b)
print(c)

tf.Tensor(12.0, shape=(), dtype=float32)


### Autograd (tf.GradientTape)

In [9]:
with tf.GradientTape() as tape:
    a = tf.Variable([1.0, 2.0, 3.0])
    b = a * 2 
    c = tf.reduce_sum(b)

grad = tape.gradient(c, a)
print(grad)

tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)


# Keras Tensors
### Create Tensors

In [10]:
from tensorflow import keras
import tensorflow as tf

x = tf.constant([[5., 6.], [7., 8.]])
print(x)

tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


### Autograd in Keras (uses TF GradientTape)

In [11]:
import tensorflow as tf

with tf.GradientTape() as tape:
    w = tf.Variable([1.0, 2.0])
    y = w * 3
grad = tape.gradient(y, w)
print(grad)

tf.Tensor([3. 3.], shape=(2,), dtype=float32)


# Tensor Operations — Universal Examples
### Reshape

In [12]:
x = torch.arange(12)
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Slicing

In [13]:
s = x[:2, 1:]
s

tensor([[1, 2, 3],
        [5, 6, 7]])

### Arithmetic

In [14]:
y = x + 10
z = x * 3

### Matrix multiplication

In [15]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 4)
out = torch.matmul(mat1, mat2)
print(out)

tensor([[ 3.3358, -0.7050, -1.4262, -1.1673],
        [-3.3162,  1.2670,  2.1095, -0.8060]])


## Exercise 1 — Create a Tensor and Move It to GPU
#### Task: Create a tensor of shape (4, 4) with random values. Move it to GPU (if available) and print device name.

In [16]:
x = torch.randn(4, 4)
x = x.to("cuda" if torch.cuda.is_available() else "cpu")
print(x.device)

cpu


## Exercise 2 — Reshape and Slice
#### Task: Create a tensor of size 12, reshape to (3,4), slice last 2 columns.

In [17]:
t = torch.arange(12).reshape(3,4)
print(t[:, 2:])

tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


## Exercise 3 — Autograd Basic

#### Task: Create tensor x = [2., 3., 4.] with requires_grad=True.
#### Compute y = x^2 + 3x.
#### Find gradients.

In [18]:
x = torch.tensor([2.,3.,4.], requires_grad=True)
y = x**2 + 3*x
y.sum().backward()
print(x.grad)

tensor([ 7.,  9., 11.])


## Exercise 4 — Matrix Multiplication

#### Task: Multiply a tensor of shape (2,3) with tensor (3,2).

In [19]:
a = torch.randn(2,3)
b = torch.randn(3,2)
print(a @ b)

tensor([[ 1.3182, -1.5827],
        [-1.1052,  3.7289]])


## Exercise 5 — TensorFlow GradientTape Practice

#### Task: In TensorFlow, compute gradient of
#### f(w) = w^3 + 2w
#### for w = [1.,2.,3.].

In [20]:
import tensorflow as tf

w = tf.Variable([1.,2.,3.])
with tf.GradientTape() as tape:
    f = w**3 + 2*w
grad = tape.gradient(f, w)
print(grad)

tf.Tensor([ 5. 14. 29.], shape=(3,), dtype=float32)
